### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by diminDDL** [ssilver2007/LiquidCrystal_1602_RUS#1]
![fdg](https://user-images.githubusercontent.com/25513498/28410879-bcc91e7c-6d47-11e7-862a-d5554d78e3df.PNG)

**Comment by ssilver2007** [comment]
Save a new sketch to the new path with new name.

**Comment by diminDDL** [comment]
I discovered that this error comes after you change the pin numbers
![inkedfdg_li](https://user-images.githubusercontent.com/25513498/28413979-41d20f16-6d52-11e7-8c62-8fc800a04450.jpg)

**Comment by ssilver2007** [comment]
Try saving the sketch under a different name. After that, compile.
