### ISSUE TITLE
How to store Russian string?

### ISSUE THREAD

**Issue by Daywer** [ssilver2007/LiquidCrystal_1602_RUS#2]
How to store a Russian string in a variable ?. Or remake the library so that only Russian characters are printed. Thanks for the library

**Comment by ssilver2007** [comment]
Russian string variable must be wchar_t type. See example SerialToLCD and library function:
wchar_t *asciiutf8(unsigned char) - convert ASCII to UTF-8 (wchar_t) string.

**Comment by Daywer** [comment]
```
#include <LiquidCrystal_1602_RUS.h>

#define display_RS     31  // Дисплей
#define display_E      33  // Дисплей
#define display_DB4    35  // Дисплей
#define display_DB5    37  // Дисплей
#define display_DB6    39  // Дисплей
#define display_DB7    41  // Дисплей

unsigned wchar_t  str = "П";

LiquidCrystal_1602_RUS lcd(display_RS, display_E, display_DB4, display_DB5, display_DB6, display_DB7); // (RS, E, DB4, DB5, DB6, DB7)
void setup()
{
  lcd.begin(16, 2);     
}

void loop() {
lcd.setCursor(0, 0);
lcd.print(lcd.asciiutf8(str));
```


Выводит символ В

**Comment by ssilver2007** [comment]
Поправьте:
wchar_t  str = L"П";

lcd.print(str);

**Comment by Daywer** [comment]
Выводит "538"

lcd.print (L"П"); Выводит как надо

**Comment by ssilver2007** [comment]
А если:
wchar_t *str = L"П";
lcd.print(str);

или:
wchar_t str = L"П";
lcd.print(&str);

**Comment by Daywer** [comment]
wchar_t *str = L"П";
lcd.print(str);

Это вариант рабочий. Огромное спасибо.
